language: php
php:
  - 5.6
  - 7.0
  - 7.1

notifications:
  email: false

install:
  composer install --no-interaction

script:
  - if [[ "$TRAVIS_PHP_VERSION" == '7.0' ]]; then composer phpcs ; fi
  - if [[ "$TRAVIS_PHP_VERSION" == '7.0' ]]; then composer phpmd ./src text phpmd; fi